language: python
python:
  - "3.10"

services:
  - docker

before_script: pip install docker-compose
#runs it before any automation script

script: 
  - docker-compose run app sh -c "python manage.py test && flake8"
#flake8 is the linting tool

